### PR TITLE
Let populate support partial population.

### PR DESCRIPTION
**Pull request by tonycurwen**
I needed support for partial population - e.g. populating only displayName on a populated user object for mean.js. Here are the code changes and a simply addition to the test cases.

### CODE REVIEW

**Comment by yolapop** [comment]
Hi @edwardhotchkiss can you publish this? This is really important
Thank you

**Comment by niftylettuce** [comment]
Released 3.1.4 to NPM

**Comment by niftylettuce** [comment]
@yolapop and @tonycurwen can you please refactor to support this https://github.com/edwardhotchkiss/mongoose-paginate/issues/40, I have deleted `3.1.4` and your merge in the meanwhile

**Comment by hbj** [comment]
I don't understand exactly the requirement, but if it is to only return the the property `displayName` of the populated `user` field, then it is already possible with:

```
[{path: user, select: 'displayName'}]
```
See http://mongoosejs.com/docs/api.html#query_Query-populate for full documentation.

**Comment by yolapop** [comment]
@hbj I guess neither @tonycurwen nor I were aware of that.

@niftylettuce so it seems the patch is not necessary, or do you think we should support the dot notation too?

**Comment by niftylettuce** [comment]
@hbj, @tonycurwen, or @yolapop please submit a PR with a patch or updated documentation for this.  Perhaps support dot notation as well?  Tests are probably needed too?  Thank you.

**Pull request merged**
