### PR TITLE
Promise support

### PR DESCRIPTION
**Pull request by tsm91**
@edwardhotchkiss @niftylettuce  for promise support i mentioned in  #51 

It won't issue any breaking change by the way.

`"mongoose-paginate": "https://github.com/tsm91/mongoose-paginate.git",`

Note:
 * I didn't write the tests, so someone should do it if you decide to merge this one. 
 * i didn't change the structure that is why i pass many arguments to handler methods
 * http://promise-nuggets.github.io/articles/11-doing-things-in-parallel.html

### CODE REVIEW

**Comment by misterdai** [comment]
This would be fantastic to have merged in.  I'm currently using Bluebird to promisify the plugin so I can easily make use of it with ES7's await keyword.

```
const [docs, pageCount, itemCount] = await Docs.paginateAsync(filters, options);
```

**Comment by tsm91** [comment]
`"mongoose-paginate": "tsm91/mongoose-paginate"` ;)

**Comment by edwardhotchkiss** [comment]
I've been using ES6 & 7 on many projects for a while. I plan on rewriting this plugin and using ES6 (ES7 is obviously still strawman features mostly). Thoughts @niftylettuce ?

**Comment by edwardhotchkiss** [comment]
➜  mongoose-paginate git:(master) npm publish
+ mongoose-paginate@4.2.0

:+1:

**Comment by tsm91** [comment]
cool

**Pull request merged**
