### PR TITLE
Reorganize settings

### PR DESCRIPTION
**Pull request by villesau**

### CODE REVIEW

**Comment by villesau** [comment]
It seems that db teardown does not complete/empty the db gracefully and causes tests to break on second try.

**Comment by niftylettuce** [comment]
@villesau Can you resolve these tests?  I'd imagine you'd want the tests working too if you rewrite it with a PR for #34.  Thanks sir!

**Comment by villesau** [comment]
@niftylettuce I can take a look at tests when i have time, but my changes didn't cause the crash. If you run the tests with clean database, tests pass. So there is an issue with either teardown or setup. The issue existed even before my PR.

**Comment by villesau** [comment]
@niftylettuce I made a fix for the tests: Now it tears down the collections before running the test, and also after running the tests. I also switched to an other assertation library. That's because the expectations and actual values are in 'wrong' order and i didn't want to change the order but to better assertation library instead.

**Pull request merged**
