### PR TITLE
mongoose-paginate 5.0.0

### PR DESCRIPTION
**Pull request by Jokero**
Support only Node.js >= 4.0
Support only Mongoose >= 4.0
Same resulting object for promise and callback
Renamed columns -> select (like in Mongoose)
Renamed sortBy -> sort (like in Mongoose)
Added offset option
Added leanWithId option
Zero limit to get only metadata
Custom default options
Mocha tests
Travis CI

### CODE REVIEW

**Comment by edwardhotchkiss** [comment]
Awesome work, thanks. Published!

**Comment by Jokero** [comment]
@edwardhotchkiss Cool! Add me please to collaborators

**Comment by edwardhotchkiss** [comment]
Just PR it bro ? :)

**Comment by Jokero** [comment]
You deprecated module and was not going to develop it. Why do you want to get PRs?

**Comment by simison** [comment]
How about transferring this for @Jokero if he is interested to maintain? I'd be really happy to see this package come alive again.

Good work both of you, thanks!

**Comment by edwardhotchkiss** [comment]
It's alive. Collaborator on npm @Jokero ?

**Comment by simison** [comment]
Man, what was this about then: https://github.com/edwardhotchkiss/mongoose-paginate/commit/36f3714d19d11f2b8f47f6841e0dfd108519613f

I mean I appreciate your work and all, but you must understand that for us to invest some time in using this plugin at our software, I have to trust this package to continue on healthy basis.

Having multiple contributors (rights at NPM + here at Github) definitely would add to trust!

BTW a v5 tag would be great. ;-)

**Comment by edwardhotchkiss** [comment]
Listen dipship (ships for nomads ya tool). You know what would be good? Learning pagination on your own. This is meant as a *leanrning tool*. Only n00bs born from n00bs use it. And tags? I could give two shits you little podracer,

**Comment by kevbook** [comment]
Haha

**Comment by edwardhotchkiss** [comment]
Oh, and Angular UI @simison - @kevbook & I started that with that piece of shit toolbox @ProLoser / enjoy your progress with a failing organization. My god. Give advice to those less senior than you.

**Comment by simison** [comment]
Uh. All the best with your projects and life, then.

**Comment by edwardhotchkiss** [comment]
As I said before: give advice to those less senior. STFU.

**Comment by kevbook** [comment]
Calm down @edwardhotchkiss ..

**Comment by edwardhotchkiss** [comment]
You mad bro @simison !? Just CALM DOWM ✌️

**Comment by Jokero** [comment]
@edwardhotchkiss Github (merge pull requests, push, add tags, ...) and npm (publish new version)

**Comment by edwardhotchkiss** [comment]
Done & Done, thanks for the great work@! 🍻

**Comment by Jokero** [comment]
@edwardhotchkiss Hmm... No changes here and in npm) I can't push to repo

**Comment by Jokero** [comment]
Is Travis enabled in repo settings? I don't see any new commits on https://travis-ci.org/edwardhotchkiss/mongoose-paginate/requests page

**Comment by Jokero** [comment]
@edwardhotchkiss ping

**Comment by edwardhotchkiss** [comment]
It seems to be using a legacy configuration. Looking into it now.

**Comment by edwardhotchkiss** [comment]
I don't see the issue but feel free to look into it and or email them: https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by Jokero** [comment]
@edwardhotchkiss I wrote to Travis support. Answer: "I've been looking into this and seems the GitHub hook got corrupted. I've gone ahead and re-established it". And now it works :)

**Comment by edwardhotchkiss** [comment]
Rad, glad it worked out! Thanks Dmitry.

Thank You,

Edward Hotchkiss

—
626.376.1661
edward@edwardhotchkiss.com
http://github.com/edwardhotchkiss/
https://www.linkedin.com/in/edwardhhotchkiss
--

**Pull request merged**
